Revise args of `$`
chocobo333/regino pull request #14
Opened 2022-05-13 14:08 UTC by Unit112358

please check whether it is correct.

2022-05-13 18:59 UTC, chocobo333 requested changes

2022-05-13 18:59 UTC, chocobo333 commented on src/il/tos.nim
>      if not self.typ.isNil:
```suggestion
if typed and not self.typ.isNil:
```

2022-05-13 18:59 UTC, chocobo333 commented on src/il/tos.nim
> +        self.comments.mapIt(`$`(it, typed, regioned, comment)).join("\n")
```suggestion
if comment:
    self.comments.mapIt(`$`(it, typed, regioned, comment)).join("\n")
else:
    ""
```

2022-05-14 07:45 UTC, Unit112358 commented on src/il/tos.nim
>      if not self.typ.isNil:
Revised

2022-05-14 08:07 UTC, Unit112358 commented on src/il/tos.nim
> +        self.comments.mapIt(`$`(it, typed, regioned, comment)).join("\n")
Revised

2022-05-14 09:16 UTC, chocobo333 approved these changes

2022-05-14 09:17 UTC, merged